# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_opepy')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_opepy')
    _opepy = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_opepy', [dirname(__file__)])
        except ImportError:
            import _opepy
            return _opepy
        try:
            _mod = imp.load_module('_opepy', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _opepy = swig_import_helper()
    del swig_import_helper
else:
    import _opepy
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0


def spherical_state_fcn(state, control, tm, mu):
    return _opepy.spherical_state_fcn(state, control, tm, mu)

def spherical_costate_fcn(state, costate, control, tm, mu):
    return _opepy.spherical_costate_fcn(state, costate, control, tm, mu)

def spherical_control_fcn(state, costate, flag):
    return _opepy.spherical_control_fcn(state, costate, flag)

def spherical_hamilton_fcn(state, costate, control, tm, mu):
    return _opepy.spherical_hamilton_fcn(state, costate, control, tm, mu)

def spherical_ext_state_fcn(ext_state, tm_p, tm_e, mu):
    return _opepy.spherical_ext_state_fcn(ext_state, tm_p, tm_e, mu)

def spherical_boundary_fcn(ext_state, tm_p, tm_e, mu):
    return _opepy.spherical_boundary_fcn(ext_state, tm_p, tm_e, mu)

def spherical_fitness_fcn(individual, k, state_p0, state_e0, tm_p, tm_e, du, tu):
    return _opepy.spherical_fitness_fcn(individual, k, state_p0, state_e0, tm_p, tm_e, du, tu)

def solve_spherical_fcn(state_p0, state_e0, tm_p, tm_e, lb, ub, k, du, tu, print):
    return _opepy.solve_spherical_fcn(state_p0, state_e0, tm_p, tm_e, lb, ub, k, du, tu, print)

# spherical_state_fcn = _opepy.spherical_state_fcn
# spherical_costate_fcn = _opepy.spherical_costate_fcn
# spherical_control_fcn = _opepy.spherical_control_fcn
# spherical_hamilton_fcn = _opepy.spherical_hamilton_fcn
# spherical_ext_state_fcn = _opepy.spherical_ext_state_fcn
# spherical_boundary_fcn = _opepy.spherical_boundary_fcn
# spherical_fitness_fcn = _opepy.spherical_fitness_fcn

# This file is compatible with both classic and new-style classes.


